# - name: Copy file
#  uses: canastro/copy-action@0.0.2

name: copy files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "list-N.json"
        target: "list-N-datasette.json"
